apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{.Values.microservices.Orderervice.serviceName}}'
  labels:
    app: '{{.Values.microservices.Orderervice.serviceName}}'
spec:
  replicas: 0
  selector:
    matchLabels:
      app: '{{.Values.microservices.Orderervice.serviceName}}'
  template:
    metadata:
      labels:
        app: '{{.Values.microservices.Orderervice.serviceName}}'
    spec:
      containers:
      - name: '{{.Values.microservices.Orderervice.serviceName}}'
        image: '{{.Values.microservices.Orderervice.dockerImage}}'
        ports:
        - containerPort: 0
        env: []
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: '{{.Values.microservices.Orderervice.maxCPU}}'
            memory: '{{.Values.microservices.Orderervice.maxMemory}}'
